apiVersion: v1
kind: PersistentVolume
metadata:
  name: torrent-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sdcard/torent"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: torrent-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi