apiVersion: v1
kind: PersistentVolume
metadata:
  name: ubuntu-pv-volume
  namespace: desktop
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/volume/ubuntu-raiz"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: desktop
  name: ubuntu-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
